pin pandas below 2.0
I get an error when starting:
```
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?
````
(sorry, lost the full backtrace).

It seems append was removed in pandas 2.0, so pinning the package for now.